In [73]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
df = pd.read_csv('Lectures/customers.csv')
print('Dataframe shape:', df.shape)
df.head()

Dataframe shape: (200, 5)

   CustomerID  Gender  Age  Salary  Spending_Score
0           1    Male   19      15              39
1           2    Male   21      15              81
2           3  Female   20      16               6
3           4  Female   23      16              77
4           5  Female   31      17              40

In [75]:
class DataProcessor:
    def __init__(self, data):
        self.data = data
    
    def preprocess_data(self):
        # Handling missing values.
        self.data.dropna(inplace=True)
        
        # Making sure age values are integers. 
        self.data['Age'] = self.data['Age'].astype(int)

    def display_data(self):
        print(self.data)

In [76]:
# Create an instance of our DataProcessor class.
processor = DataProcessor(df)

processor.preprocess_data()

processor.display_data()

     CustomerID  Gender  Age  Salary  Spending_Score
0             1    Male   19      15              39
1             2    Male   21      15              81
2             3  Female   20      16               6
3             4  Female   23      16              77
4             5  Female   31      17              40
..          ...     ...  ...     ...             ...
195         196  Female   35     120              79
196         197  Female   45     126              28
197         198    Male   32     126              74
198         199    Male   32     137              18
199         200    Male   30     137              83

[200 rows x 5 columns]

In [77]:
# Example 2: Custom data transformation class

class DataTransformer:
    def __init__(self, data):
        self.data = data
    
    def transform_age(self):
        def categorize_age(age):
            if age < 30:
                return 'Young'
            elif 30 <= age <= 60:
                return 'Middle-aged'
            else:
                return 'Old'
        
        self.data['Age_Group'] = self.data['Age'].apply(categorize_age) # Very important line of code!

In [78]:
transfromer = DataTransformer(df)

transfromer.transform_age()

print(transfromer.data)

     CustomerID  Gender  Age  Salary  Spending_Score    Age_Group
0             1    Male   19      15              39        Young
1             2    Male   21      15              81        Young
2             3  Female   20      16               6        Young
3             4  Female   23      16              77        Young
4             5  Female   31      17              40  Middle-aged
..          ...     ...  ...     ...             ...          ...
195         196  Female   35     120              79  Middle-aged
196         197  Female   45     126              28  Middle-aged
197         198    Male   32     126              74  Middle-aged
198         199    Male   32     137              18  Middle-aged
199         200    Male   30     137              83  Middle-aged

[200 rows x 6 columns]

In [79]:
# Data analysis class

class DataAnalysis:
    def __init__(self, data):
        self.data = data
    
    def summary_statistics(self):
        summary = {
        'mean_age': self.data['Age'].mean(),
        'median_age': self.data['Age'].median(),
        'min_age': self.data['Age'].min(),
        'max_age': self.data['Age'].max()
        }

        return summary
    
test = DataAnalysis(df)

print(test.summary_statistics())

{'mean_age': np.float64(38.85), 'median_age': np.float64(36.0), 'min_age': np.int64(18), 'max_age': np.int64(70)}

In [ ]:
# Example 4: Advanced data set analyzer. 

class AdvDataAnalyzer:
    def __init__(self, data:pd.DataFrame):
        self.data = data
    
    def dataset_dimension(self):
        return self.data.shape
    
    def column_names(self):
        return self.data.columns.to_list()
    
    def dataframe_head(self, rows=10):
        return self.data.head(rows)

    def dataframe_tail(self, rows=10):
        return self.data.tail(rows)
    
class SpecialAnalyzer(AdvDataAnalyzer):
    def check_missing_values(self):
        return self.data.isnull().sum()
    
    def check_duplicate_values(self):
        return self.data.duplicated().sum()
    
    def remove_duplicates(self):
        return self.data.drop_duplicates()
    
    def fill_missing(self, value=0):
        return self.data.fillna(value) # How to do with with the mean value?
    
    def summary_statistics(self):
        return self.data.describe()

advanced_data_analyzer = AdvDataAnalyzer(df)

advanced_data_analyzer.dataframe_head()

   CustomerID  Gender  Age  Salary  Spending_Score    Age_Group
0           1    Male   19      15              39        Young
1           2    Male   21      15              81        Young
2           3  Female   20      16               6        Young
3           4  Female   23      16              77        Young
4           5  Female   31      17              40  Middle-aged
5           6  Female   22      17              76        Young
6           7  Female   35      18               6  Middle-aged
7           8  Female   23      18              94        Young
8           9    Male   64      19               3          Old
9          10  Female   30      19              72  Middle-aged