# Getting started with Datasets

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving covid.csv to covid.csv

In [ ]:
import pandas as pd
data_csv=pd.read_csv('covid.csv') # read the csv file.

# pd.read_excel; pd.read_json; pd.read_sas; pd.read_spss

In [ ]:
### Before that find and print working dirctory
import os

In [ ]:
os.getcwd()

'/content'

In [ ]:
!ls

covid.csv  sample_data

In [ ]:
import pandas as pd
import numpy as np

covid_df=pd.read_csv('covid.csv')

In [ ]:
covid_df.head() # views the top 10 lines. the defult value is 5.

,date,state,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
0,2021-02-23,AK,290.0,NaN,0,NaN,1260.0,1260.0,38.0,9,...,1653425.0,4640,NaN,NaN,NaN,NaN,NaN,0,1653425.0,4640
1,2021-02-23,AL,9660.0,7575.0,68,2085.0,45250.0,45250.0,762.0,122,...,2265086.0,4825,NaN,NaN,115256.0,NaN,2265086.0,4825,NaN,0
2,2021-02-23,AR,5377.0,4321.0,14,1056.0,14617.0,14617.0,545.0,47,...,2609837.0,4779,NaN,NaN,NaN,436309.0,NaN,0,2609837.0,4779
3,2021-02-23,AS,0.0,NaN,0,NaN,NaN,NaN,NaN,0,...,2140.0,0,NaN,NaN,NaN,NaN,NaN,0,2140.0,0
4,2021-02-23,AZ,15650.0,13821.0,148,1829.0,57072.0,57072.0,1515.0,78,...,7478323.0,19439,435091.0,NaN,NaN,NaN,3709365.0,6212,7478323.0,19439

In [ ]:
covid_df.tail()

,date,state,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
20103,2020-01-17,WA,NaN,NaN,0,NaN,NaN,NaN,NaN,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
20104,2020-01-16,WA,NaN,NaN,0,NaN,NaN,NaN,NaN,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
20105,2020-01-15,WA,NaN,NaN,0,NaN,NaN,NaN,NaN,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
20106,2020-01-14,WA,NaN,NaN,0,NaN,NaN,NaN,NaN,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0
20107,2020-01-13,WA,NaN,NaN,0,NaN,NaN,NaN,NaN,0,...,NaN,0,NaN,NaN,NaN,NaN,NaN,0,NaN,0

In [ ]:
len(covid_df)

20108

In [ ]:
covid_df.shape # row,column length

(20108, 41)

In [ ]:
np.shape(covid_df)

(20108, 41)

In [ ]:
covid_df.columns #views the column names

Index(['date', 'state', 'death', 'deathConfirmed', 'deathIncrease',
       'deathProbable', 'hospitalized', 'hospitalizedCumulative',
       'hospitalizedCurrently', 'hospitalizedIncrease', 'inIcuCumulative',
       'inIcuCurrently', 'negative', 'negativeIncrease',
       'negativeTestsAntibody', 'negativeTestsPeopleAntibody',
       'negativeTestsViral', 'onVentilatorCumulative', 'onVentilatorCurrently',
       'positive', 'positiveCasesViral', 'positiveIncrease', 'positiveScore',
       'positiveTestsAntibody', 'positiveTestsAntigen',
       'positiveTestsPeopleAntibody', 'positiveTestsPeopleAntigen',
       'positiveTestsViral', 'recovered', 'totalTestEncountersViral',
       'totalTestEncountersViralIncrease', 'totalTestResults',
       'totalTestResultsIncrease', 'totalTestsAntibody', 'totalTestsAntigen',
       'totalTestsPeopleAntibody', 'totalTestsPeopleAntigen',
       'totalTestsPeopleViral', 'totalTestsPeopleViralIncrease',
       'totalTestsViral', 'totalTestsViralIncrease'],
      dtype='object')

In [ ]:
covid_df.info() ## information on the columns. Like the str function

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20108 entries, 0 to 20107
Data columns (total 41 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   date                              20108 non-null  object
 1   state                             20108 non-null  object
 2   death                             19230 non-null  float64
 3   deathConfirmed                    9407 non-null   float64
 4   deathIncrease                     20108 non-null  int64
 5   deathProbable                     7249 non-null   float64
 6   hospitalized                      12435 non-null  float64
 7   hospitalizedCumulative            12435 non-null  float64
 8   hospitalizedCurrently             16702 non-null  float64
 9   hospitalizedIncrease              20108 non-null  int64
 10  inIcuCumulative                   3648 non-null   float64
 11  inIcuCurrently                    11030 non-null  float64
 12  negative                          15640 non-null  float64
 13  negativeIncrease                  20108 non-null  int64
 14  negativeTestsAntibody             1469 non-null   float64
 15  negativeTestsPeopleAntibody       936 non-null    float64
 16  negativeTestsViral                5046 non-null   float64
 17  onVentilatorCumulative            1245 non-null   float64
 18  onVentilatorCurrently             8738 non-null   float64
 19  positive                          19912 non-null  float64
 20  positiveCasesViral                13510 non-null  float64
 21  positiveIncrease                  20108 non-null  int64
 22  positiveScore                     20108 non-null  int64
 23  positiveTestsAntibody             3274 non-null   float64
 24  positiveTestsAntigen              2054 non-null   float64
 25  positiveTestsPeopleAntibody       1046 non-null   float64
 26  positiveTestsPeopleAntigen        597 non-null    float64
 27  positiveTestsViral                8149 non-null   float64
 28  recovered                         11594 non-null  float64
 29  totalTestEncountersViral          5063 non-null   float64
 30  totalTestEncountersViralIncrease  20108 non-null  int64
 31  totalTestResults                  20006 non-null  float64
 32  totalTestResultsIncrease          20108 non-null  int64
 33  totalTestsAntibody                4604 non-null   float64
 34  totalTestsAntigen                 3146 non-null   float64
 35  totalTestsPeopleAntibody          1811 non-null   float64
 36  totalTestsPeopleAntigen           939 non-null    float64
 37  totalTestsPeopleViral             8904 non-null   float64
 38  totalTestsPeopleViralIncrease     20108 non-null  int64
 39  totalTestsViral                   13404 non-null  float64
 40  totalTestsViralIncrease           20108 non-null  int64
dtypes: float64(30), int64(9), object(2)
memory usage: 6.3+ MB

In [ ]:
covid_df.describe()

,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,...,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease
count,19230.000000,9407.000000,20108.000000,7249.000000,12435.000000,12435.000000,16702.000000,20108.000000,3648.000000,11030.000000,...,2.000600e+04,20108.000000,4604.000000,3.146000e+03,1811.000000,939.000000,8.904000e+03,2.010800e+04,1.340400e+04,2.010800e+04
mean,3500.500624,3482.964601,24.498856,388.324872,10894.789867,10894.789867,1202.387020,42.749552,1860.788651,357.389574,...,2.040582e+06,17231.037597,152900.536924,2.686660e+05,141513.062949,153591.400426,9.242205e+05,2.758912e+03,2.260072e+06,1.283705e+04
std,5959.535751,3970.362837,59.514726,501.534437,17255.212783,17255.212783,2082.181692,213.225911,1877.529448,593.114246,...,4.140028e+06,33238.279313,187239.659156,3.741479e+05,170220.886689,132933.649942,1.353812e+06,2.195395e+04,4.234157e+06,3.909861e+04
min,0.000000,0.000000,-201.000000,0.000000,1.000000,1.000000,0.000000,-4124.000000,6.000000,0.000000,...,0.000000e+00,-194215.000000,0.000000,1.000000e+00,1.000000,3.000000,0.000000e+00,-1.122327e+06,0.000000e+00,-1.154583e+06
25%,152.000000,477.500000,0.000000,72.000000,988.000000,988.000000,168.000000,0.000000,479.000000,61.000000,...,9.323125e+04,1074.000000,17765.000000,1.700675e+04,42170.000000,34343.000000,1.378798e+05,0.000000e+00,1.645438e+05,0.000000e+00
50%,1042.000000,2142.000000,6.000000,210.000000,4670.000000,4670.000000,535.000000,0.000000,1258.000000,171.000000,...,6.052765e+05,5968.000000,80982.000000,1.061260e+05,86536.000000,131236.000000,4.058435e+05,0.000000e+00,7.836605e+05,1.432500e+03
75%,4151.750000,5041.500000,23.000000,410.000000,12470.500000,12470.500000,1295.000000,37.000000,2389.000000,379.000000,...,2.114858e+06,18703.250000,216860.500000,3.819570e+05,139022.000000,233430.000000,1.173336e+06,2.564250e+03,2.474755e+06,1.213225e+04
max,49563.000000,20689.000000,2559.000000,2538.000000,89995.000000,89995.000000,22851.000000,16373.000000,8967.000000,5225.000000,...,4.751337e+07,473076.000000,997580.000000,2.341176e+06,946648.000000,543942.000000,1.089583e+07,8.982590e+05,4.751337e+07,2.164543e+06

In [ ]:
covid_df.describe().transpose() # or T

,count,mean,std,min,25%,50%,75%,max
death,19230.0,3.500501e+03,5.959536e+03,0.0,152.00,1042.0,4151.75,49563.0
deathConfirmed,9407.0,3.482965e+03,3.970363e+03,0.0,477.50,2142.0,5041.50,20689.0
deathIncrease,20108.0,2.449886e+01,5.951473e+01,-201.0,0.00,6.0,23.00,2559.0
deathProbable,7249.0,3.883249e+02,5.015344e+02,0.0,72.00,210.0,410.00,2538.0
hospitalized,12435.0,1.089479e+04,1.725521e+04,1.0,988.00,4670.0,12470.50,89995.0
hospitalizedCumulative,12435.0,1.089479e+04,1.725521e+04,1.0,988.00,4670.0,12470.50,89995.0
hospitalizedCurrently,16702.0,1.202387e+03,2.082182e+03,0.0,168.00,535.0,1295.00,22851.0
hospitalizedIncrease,20108.0,4.274955e+01,2.132259e+02,-4124.0,0.00,0.0,37.00,16373.0
inIcuCumulative,3648.0,1.860789e+03,1.877529e+03,6.0,479.00,1258.0,2389.00,8967.0
inIcuCurrently,11030.0,3.573896e+02,5.931142e+02,0.0,61.00,171.0,379.00,5225.0
negative,15640.0,1.037231e+06,1.791414e+06,0.0,64885.00,340270.5,1218568.25,16544241.0
negativeIncrease,20108.0,5.982636e+03,1.501094e+04,-968686.0,0.00,1294.5,6710.25,212974.0
negativeTestsAntibody,1469.0,1.332013e+05,1.788387e+05,587.0,11242.00,71287.0,153766.00,831212.0
negativeTestsPeopleAntibody,936.0,1.822878e+05,1.913099e+05,1.0,53078.25,93746.0,235304.50,790547.0
negativeTestsViral,5046.0,1.665249e+06,2.328751e+06,1.0,267730.75,849796.0,2109523.75,16175417.0
onVentilatorCumulative,1245.0,5.545149e+02,4.219861e+02,32.0,211.00,411.0,788.00,1505.0
onVentilatorCurrently,8738.0,1.538970e+02,2.101454e+02,0.0,29.00,87.0,188.00,2425.0
positive,19912.0,1.536619e+05,3.044856e+05,0.0,5309.50,42812.0,166495.00,3450058.0
positiveCasesViral,13510.0,1.700394e+05,3.151447e+05,0.0,10611.50,67058.0,193420.50,3450058.0
positiveIncrease,20108.0,1.392571e+03,3.058254e+03,-7757.0,63.00,433.0,1336.25,71734.0
positiveScore,20108.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.00,0.0
positiveTestsAntibody,3274.0,1.785654e+04,2.560355e+04,0.0,852.00,7803.0,23182.00,165482.0
positiveTestsAntigen,2054.0,2.779218e+04,3.702777e+04,0.0,1085.00,11823.5,42030.50,194246.0
positiveTestsPeopleAntibody,1046.0,1.882404e+04,2.534252e+04,0.0,3085.50,11517.0,18780.00,155757.0
positiveTestsPeopleAntigen,597.0,2.289043e+04,2.261434e+04,3.0,2416.00,14743.0,41752.00,77812.0
positiveTestsViral,8149.0,1.948158e+05,3.378460e+05,0.0,17041.00,65879.0,220917.00,2568513.0
recovered,11594.0,8.642751e+04,1.933303e+05,2.0,3226.50,15974.0,88333.00,2353741.0
totalTestEncountersViral,5063.0,2.524134e+06,4.725660e+06,0.0,179997.00,838627.0,2603305.00,36760944.0
totalTestEncountersViralIncrease,20108.0,5.431692e+03,2.055805e+04,-16946.0,0.00,0.0,0.00,324671.0
totalTestResults,20006.0,2.040582e+06,4.140028e+06,0.0,93231.25,605276.5,2114857.50,47513367.0
totalTestResultsIncrease,20108.0,1.723104e+04,3.323828e+04,-194215.0,1074.00,5968.0,18703.25,473076.0
totalTestsAntibody,4604.0,1.529005e+05,1.872397e+05,0.0,17765.00,80982.0,216860.50,997580.0
totalTestsAntigen,3146.0,2.686660e+05,3.741479e+05,1.0,17006.75,106126.0,381957.00,2341176.0
totalTestsPeopleAntibody,1811.0,1.415131e+05,1.702209e+05,1.0,42170.00,86536.0,139022.00,946648.0
totalTestsPeopleAntigen,939.0,1.535914e+05,1.329336e+05,3.0,34343.00,131236.0,233430.00,543942.0
totalTestsPeopleViral,8904.0,9.242205e+05,1.353812e+06,0.0,137879.75,405843.5,1173336.50,10895833.0
totalTestsPeopleViralIncrease,20108.0,2.758912e+03,2.195395e+04,-1122327.0,0.00,0.0,2564.25,898259.0
totalTestsViral,13404.0,2.260072e+06,4.234157e+06,0.0,164543.75,783660.5,2474755.00,47513367.0
totalTestsViralIncrease,20108.0,1.283705e+04,3.909861e+04,-1154583.0,0.00,1432.5,12132.25,2164543.0

In [ ]:
# sub data set

sub_covid_df=pd.read_csv('covid.csv',usecols=['date','state','positive','negative','totalTestResults'],parse_dates=['date'],infer_datetime_format=True)
sub_covid_df.head()
# infer_datetime_format parameter tells pandas to automatically detect the datetime format used in the date columns specified by parse_dates

/tmp/ipykernel_1664/1417930307.py:3: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  sub_covid_df=pd.read_csv('covid.csv',usecols=['date','state','positive','negative','totalTestResults'],parse_dates=['date'],infer_datetime_format=True)

        date state   negative  positive  totalTestResults
0 2021-02-23    AK        NaN   55560.0         1653425.0
1 2021-02-23    AL  1882180.0  488973.0         2265086.0
2 2021-02-23    AR  2359571.0  316593.0         2609837.0
3 2021-02-23    AS     2140.0       0.0            2140.0
4 2021-02-23    AZ  2953210.0  810658.0         7478323.0

In [ ]:
sub_covid_df[30:36]

         date state   negative  positive  totalTestResults
30 2021-02-23    NC  9249147.0  846284.0        10095431.0
31 2021-02-23    ND   303267.0   99416.0         1395829.0
32 2021-02-23    NE   758267.0  199402.0         2323010.0
33 2021-02-23    NH   571901.0   73923.0         1413885.0
34 2021-02-23    NJ  9674485.0  772267.0        10446752.0
35 2021-02-23    NM  2444482.0  183335.0         2627817.0

In [ ]:
sub_covid_df[: :-1]

            date state   negative  positive  totalTestResults
20107 2020-01-13    WA        NaN       NaN               NaN
20106 2020-01-14    WA        NaN       0.0               NaN
20105 2020-01-15    WA        NaN       0.0               NaN
20104 2020-01-16    WA        NaN       0.0               NaN
20103 2020-01-17    WA        NaN       0.0               NaN
...          ...   ...        ...       ...               ...
4     2021-02-23    AZ  2953210.0  810658.0         7478323.0
3     2021-02-23    AS     2140.0       0.0            2140.0
2     2021-02-23    AR  2359571.0  316593.0         2609837.0
1     2021-02-23    AL  1882180.0  488973.0         2265086.0
0     2021-02-23    AK        NaN   55560.0         1653425.0

[20108 rows x 5 columns]

In [ ]:
sub_covid_df[: : 5]

            date state   negative   positive  totalTestResults
0     2021-02-23    AK        NaN    55560.0         1653425.0
5     2021-02-23    CA        NaN  3450058.0        47513367.0
10    2021-02-23    FL  9051605.0  1844228.0        21264199.0
15    2021-02-23    ID   494773.0   169584.0          632561.0
20    2021-02-23    LA  5020119.0   426048.0         5446167.0
...          ...   ...        ...        ...               ...
20085 2020-01-28    WA        NaN        2.0               0.0
20090 2020-01-26    WA        NaN        2.0               0.0
20095 2020-01-23    MA        NaN        NaN               2.0
20100 2020-01-20    WA        NaN        1.0               NaN
20105 2020-01-15    WA        NaN        0.0               NaN

[4022 rows x 5 columns]

In [ ]:
sub_covid_df.columns

Index(['date', 'state', 'negative', 'positive', 'totalTestResults'], dtype='object')

In [ ]:
sub_covid_df.columns=['date2','state2','negative','positive','totalTestResults']

In [ ]:
sub_covid_df.columns

Index(['date2', 'state2', 'negative', 'positive', 'totalTestResults'], dtype='object')

In [ ]:
sub_covid_df.state2

0        AK
1        AL
2        AR
3        AS
4        AZ
         ..
20103    WA
20104    WA
20105    WA
20106    WA
20107    WA
Name: state2, Length: 20108, dtype: object

In [ ]:
sub_covid_df['state2'].head()

0    AK
1    AL
2    AR
3    AS
4    AZ
Name: state2, dtype: object

In [ ]:
sub_covid_df['mycalc']=sub_covid_df.positive*covid_df.negative
sub_covid_df

           date2 state2   negative  positive  totalTestResults        mycalc
0     2021-02-23     AK        NaN   55560.0         1653425.0           NaN
1     2021-02-23     AL  1882180.0  488973.0         2265086.0  9.203352e+11
2     2021-02-23     AR  2359571.0  316593.0         2609837.0  7.470237e+11
3     2021-02-23     AS     2140.0       0.0            2140.0  0.000000e+00
4     2021-02-23     AZ  2953210.0  810658.0         7478323.0  2.394043e+12
...          ...    ...        ...       ...               ...           ...
20103 2020-01-17     WA        NaN       0.0               NaN           NaN
20104 2020-01-16     WA        NaN       0.0               NaN           NaN
20105 2020-01-15     WA        NaN       0.0               NaN           NaN
20106 2020-01-14     WA        NaN       0.0               NaN           NaN
20107 2020-01-13     WA        NaN       NaN               NaN           NaN

[20108 rows x 6 columns]

In [ ]:
## Removing a columns
sub_covid_df.drop('mycalc',axis=1)

           date2 state2   negative  positive  totalTestResults
0     2021-02-23     AK        NaN   55560.0         1653425.0
1     2021-02-23     AL  1882180.0  488973.0         2265086.0
2     2021-02-23     AR  2359571.0  316593.0         2609837.0
3     2021-02-23     AS     2140.0       0.0            2140.0
4     2021-02-23     AZ  2953210.0  810658.0         7478323.0
...          ...    ...        ...       ...               ...
20103 2020-01-17     WA        NaN       0.0               NaN
20104 2020-01-16     WA        NaN       0.0               NaN
20105 2020-01-15     WA        NaN       0.0               NaN
20106 2020-01-14     WA        NaN       0.0               NaN
20107 2020-01-13     WA        NaN       NaN               NaN

[20108 rows x 5 columns]

In [ ]:
# sub data set

sub_covid_df=pd.read_csv('covid.csv',usecols=['date','state','death','positive','negative','totalTestResults'],parse_dates=['date'],infer_datetime_format=True)
sub_covid_df.head()

/tmp/ipykernel_1664/1636697777.py:3: FutureWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  sub_covid_df=pd.read_csv('covid.csv',usecols=['date','state','death','positive','negative','totalTestResults'],parse_dates=['date'],infer_datetime_format=True)

        date state    death   negative  positive  totalTestResults
0 2021-02-23    AK    290.0        NaN   55560.0         1653425.0
1 2021-02-23    AL   9660.0  1882180.0  488973.0         2265086.0
2 2021-02-23    AR   5377.0  2359571.0  316593.0         2609837.0
3 2021-02-23    AS      0.0     2140.0       0.0            2140.0
4 2021-02-23    AZ  15650.0  2953210.0  810658.0         7478323.0

In [ ]:
# Problem with Null values
#isnull

pd.isnull(sub_covid_df)

        date  state  death  negative  positive  totalTestResults
0      False  False  False      True     False             False
1      False  False  False     False     False             False
2      False  False  False     False     False             False
3      False  False  False     False     False             False
4      False  False  False     False     False             False
...      ...    ...    ...       ...       ...               ...
20103  False  False   True      True     False              True
20104  False  False   True      True     False              True
20105  False  False   True      True     False              True
20106  False  False   True      True     False              True
20107  False  False   True      True      True              True

[20108 rows x 6 columns]

In [ ]:
# To select just the rows with NaN values, we can use "any()" method

sub_covid_df[pd.isnull(sub_covid_df).any(axis=1)]

            date state    death  negative   positive  totalTestResults
0     2021-02-23    AK    290.0       NaN    55560.0         1653425.0
5     2021-02-23    CA  49563.0       NaN  3450058.0        47513367.0
7     2021-02-23    CT   7572.0       NaN   276691.0         6198707.0
8     2021-02-23    DC    998.0       NaN    39844.0         1201605.0
11    2021-02-23    GA  16927.0       NaN   990821.0         7076399.0
...          ...   ...      ...       ...        ...               ...
20103 2020-01-17    WA      NaN       NaN        0.0               NaN
20104 2020-01-16    WA      NaN       NaN        0.0               NaN
20105 2020-01-15    WA      NaN       NaN        0.0               NaN
20106 2020-01-14    WA      NaN       NaN        0.0               NaN
20107 2020-01-13    WA      NaN       NaN        NaN               NaN

[4970 rows x 6 columns]

In [ ]:
# checking for missing values
print(sub_covid_df.isnull().sum())

date                   0
state                  0
death                878
negative            4468
positive             196
totalTestResults     102
dtype: int64

In [ ]:
#Calculate the percentage of missing values for each column
missing_percentage=sub_covid_df.isnull().mean()*100
print(missing_percentage)

date                 0.000000
state                0.000000
death                4.366421
negative            22.220012
positive             0.974736
totalTestResults     0.507261
dtype: float64

In [ ]:
#Drop rows with any missing values
sub_covid_df.dropna(inplace=True)
sub_covid_df

            date state    death   negative  positive  totalTestResults
1     2021-02-23    AL   9660.0  1882180.0  488973.0         2265086.0
2     2021-02-23    AR   5377.0  2359571.0  316593.0         2609837.0
3     2021-02-23    AS      0.0     2140.0       0.0            2140.0
4     2021-02-23    AZ  15650.0  2953210.0  810658.0         7478323.0
6     2021-02-23    CO   5907.0  2143029.0  422390.0         6043583.0
...          ...   ...      ...        ...       ...               ...
19708 2020-03-08    NJ      0.0       31.0       6.0              37.0
19710 2020-03-08    NV      0.0       14.0       4.0             103.0
19761 2020-03-07    NV      0.0       14.0       4.0              73.0
19804 2020-03-06    NV      0.0       14.0       3.0              48.0
19837 2020-03-05    NV      0.0       14.0       1.0              32.0

[15138 rows x 6 columns]

In [ ]:
# Drop rows with missing values in specific columns e.g: death and positive
sub_covid_df.dropna(subset=['death','positive'],inplace=True)
sub_covid_df

            date state    death   negative  positive  totalTestResults
0     2021-02-23    AK    290.0        NaN   55560.0         1653425.0
1     2021-02-23    AL   9660.0  1882180.0  488973.0         2265086.0
2     2021-02-23    AR   5377.0  2359571.0  316593.0         2609837.0
3     2021-02-23    AS      0.0     2140.0       0.0            2140.0
4     2021-02-23    AZ  15650.0  2953210.0  810658.0         7478323.0
...          ...   ...      ...        ...       ...               ...
19914 2020-03-01    WA      8.0        NaN      26.0             117.0
19923 2020-02-29    WA      5.0        NaN      18.0              42.0
19930 2020-02-28    WA      4.0        NaN      15.0               0.0
19937 2020-02-27    WA      2.0        NaN      13.0               0.0
19943 2020-02-26    WA      2.0        NaN      12.0               0.0

[19182 rows x 6 columns]

In [ ]:
# Fill missing values with 0
sub_covid_df.fillna(0,inplace=True)
sub_covid_df

            date state    death   negative  positive  totalTestResults
0     2021-02-23    AK    290.0        0.0   55560.0         1653425.0
1     2021-02-23    AL   9660.0  1882180.0  488973.0         2265086.0
2     2021-02-23    AR   5377.0  2359571.0  316593.0         2609837.0
3     2021-02-23    AS      0.0     2140.0       0.0            2140.0
4     2021-02-23    AZ  15650.0  2953210.0  810658.0         7478323.0
...          ...   ...      ...        ...       ...               ...
19914 2020-03-01    WA      8.0        0.0      26.0             117.0
19923 2020-02-29    WA      5.0        0.0      18.0              42.0
19930 2020-02-28    WA      4.0        0.0      15.0               0.0
19937 2020-02-27    WA      2.0        0.0      13.0               0.0
19943 2020-02-26    WA      2.0        0.0      12.0               0.0

[19182 rows x 6 columns]

In [ ]:
#Fill Missing values with the Mean, Median, Mode
sub_covid_df['death']=sub_covid_df['death'].fillna(sub_covid_df['death'].mean())
sub_covid_df['positive']=sub_covid_df['positive'].fillna(sub_covid_df['positive'].median())
sub_covid_df['state']=sub_covid_df['state'].fillna(sub_covid_df['state'].mode()[0])

In [ ]:
#checking for duplicates
print(sub_covid_df.duplicated().sum())

0

In [ ]:
# Drop duplicated rows, if any:
sub_covid_df.drop_duplicates(inplace=True)

In [ ]:
# Write DateFrame to outfile

sub_covid_df.to_csv('sub_covid_df.csv')

In [ ]:
sub_covid_df=sub_covid_df.sort_values(by='date')
sub_covid_df

            date state    death    negative   positive  totalTestResults
19943 2020-02-26    WA      2.0         0.0       12.0               0.0
19937 2020-02-27    WA      2.0         0.0       13.0               0.0
19930 2020-02-28    WA      4.0         0.0       15.0               0.0
19923 2020-02-29    WA      5.0         0.0       18.0              42.0
19914 2020-03-01    WA      8.0         0.0       26.0             117.0
...          ...   ...      ...         ...        ...               ...
16    2021-02-23    IL  22528.0  16544241.0  1177320.0        17721561.0
45    2021-02-23    SD   1863.0    307241.0   111546.0          418787.0
49    2021-02-23    VA   7658.0         0.0   567039.0         5778994.0
15    2021-02-23    ID   1826.0    494773.0   169584.0          632561.0
0     2021-02-23    AK    290.0         0.0    55560.0         1653425.0

[19182 rows x 6 columns]

In [ ]:
sub_covid_df['date']=pd.to_datetime(sub_covid_df['date'],yearfirst=True)
sub_covid_df

            date state    death    negative   positive  totalTestResults
19943 2020-02-26    WA      2.0         0.0       12.0               0.0
19937 2020-02-27    WA      2.0         0.0       13.0               0.0
19930 2020-02-28    WA      4.0         0.0       15.0               0.0
19923 2020-02-29    WA      5.0         0.0       18.0              42.0
19914 2020-03-01    WA      8.0         0.0       26.0             117.0
...          ...   ...      ...         ...        ...               ...
16    2021-02-23    IL  22528.0  16544241.0  1177320.0        17721561.0
45    2021-02-23    SD   1863.0    307241.0   111546.0          418787.0
49    2021-02-23    VA   7658.0         0.0   567039.0         5778994.0
15    2021-02-23    ID   1826.0    494773.0   169584.0          632561.0
0     2021-02-23    AK    290.0         0.0    55560.0         1653425.0

[19182 rows x 6 columns]